version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  storage-service:
    build:
      context: .
      dockerfile: StorageService/Dockerfile
    environment:
      - HOSTNAMERABBIT=rabbitmq
    depends_on:
      - rabbitmq
    restart: always
    volumes:
      - storage_service_data:/tmp

  pixel-service:
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: PixelService/Dockerfile
    depends_on:
      - rabbitmq
    links: 
      - rabbitmq
    restart: always
    ports:
      - "8080:80"   # HTTP
volumes:
  rabbitmq_data:
  storage_service_data:  